[package]
name = "rust_vst3"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "28b149ec", features = ["assert_process_allocs"] }

[workspace]
members = ["xtask"]

[profile.release]
lto = "thin"
strip = "symbols"
